sudo: required
dist: trusty
language: node_js
node_js:
  - node

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - sudo pip install awscli
  - npm install --no-optional

cache:
  - directories: node_modules
    
script:
  - npm test
  - codecov
  - chmod +x ./travis-deploy/deploy.sh
  - ./travis-deploy/deploy.sh
