sudo: required
language: node_js
node_js:
  - node

install:
  - npm i -g serverless
  - npm i -g @angular/cli
  - npm install --no-optional

cache:
  - directories:
      - node_modules
      - $(npm config get prefix)/bin/@angular/cli
      - $(npm config get prefix)/bin/serverless
    
script:
  - chmod +x ./travis-deploy.sh
  - ./travis-deploy.sh

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: phillip.santaswap.io
  skip_cleanup: true
  local_dir: dist
  detect_encoding: true
  on:
    all_branches: true
