version: 0.1

phases:
  install:
    commands:
      - npm i
      - echo Getting api endpoints for the $STAGE environment
      # Need to save variables in a text file because can't persist environment variables in this context
      - aws cloudformation describe-stacks --stack-name Groups-$STAGE --query 'Stacks[0].Outputs[?OutputKey==`GroupsEndpoint`].OutputValue' --output text > groupsEndpoint.txt
      - echo Setting groups endpoint as $(cat groupsEndpoint.txt)
      - aws cloudformation describe-stacks --stack-name Users-$STAGE --query 'Stacks[0].Outputs[?OutputKey==`UsersEndpoint`].OutputValue' --output text > usersEndpoint.txt
      - echo Setting users endpoint as $(cat usersEndpoint.txt)
  build:
    commands:
      # Replace the placeholder value for each endpoint in the prod config file before it's built
      - sed -i "s|GROUPS_ENDPOINT|$(cat groupsEndpoint.txt)|g" src/environments/environment.prod.ts
      - sed -i "s|USERS_ENDPOINT|$(cat usersEndpoint.txt)|g" src/environments/environment.prod.ts
      - npm run build

artifacts:
  files:
    - dist/*
  discard-paths: yes
