# Note: YAML anchors allow an object to be re-used, reducing duplication. The ampersand
# declares an alias for an object, then later the `<<: *alias` syntax dereferences it.
#
# See http://blog.daemonl.com/2016/02/yaml.html and
# https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd
# for more information about how to use anchors.
#
# To validate changes use an online parser, eg. http://yaml-online-parser.appspot.com/
anchors:
  container-config: &container-config
    docker:
      - image: circleci/node:10-browsers
        environment:
          TERM: dumb

  cache-dependencies: &cache-dependencies
    save_cache:
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - node_modules

  load-dependency-cache: &load-dependency-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}

  cache-build: &cache-build
    save_cache:
      key: build-cache-{{ .Branch }}-{{ .Revision }}
      paths:
        - dist

  load-build-cache: &load-build-cache
    restore_cache:
      key: build-cache-{{ .Branch }}-{{ .Revision }}

## Circle CI configuration, see https://circleci.com/docs/2.0/configuration-reference/
version: 2
jobs:
  install-dependencies:
    <<: *container-config
    steps:
      - checkout
      - *load-dependency-cache
      - run:
          name: Install dependencies
          command: npm i
      - *cache-dependencies

  test-site:
    <<: *container-config
    steps:
      - checkout
      - *load-dependency-cache
      - run:
          name: Rebuild node-sass
          command: npm rebuild node-sass
      - run:
          name: Run tests
          command: npm run test:ci

  build-site:
    <<: *container-config
    steps:
      - checkout
      - *load-dependency-cache
      - run:
          name: Build site
          command: npm run build:ci
      - *cache-build

  build-site-infrastructure:
    <<: *container-config
    steps:
      - checkout
      - *load-dependency-cache
      - run:
          name: Build site infrastructure
          command: echo 'Building site infrastructure'

  deploy-site:
    <<: *container-config
    steps:
      - checkout
      - *load-dependency-cache
      - *load-build-cache
      - run:
          name: Deploy site
          command: echo 'Deploying site'

workflows:
  version: 2
  test:
    jobs:
      - install-dependencies
      - test-site:
          requires:
            - install-dependencies
      - build-site:
          requires:
            - test-site
      - build-site-infrastructure:
          requires:
            - build-site
      - deploy-site:
          requires:
            - build-site-infrastructure
