AWSTemplateFormatVersion: "2010-09-09"
Description: Infrastructure for static UI

Parameters:
  Project:
    Description: Name of the project (e.g. SantaSwap)
    Type: String
  Domain:
    Description: Naked site domain name (e.g. manwaring.io)
    Type: String
  HostedZoneId:
    Description: ID of the hosted zone for the domain
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Project settings"
        Parameters:
          - Project
      - Label:
          default: "Site settings"
        Parameters:
          - Domain
          - HostedZoneId

Mappings:
  Constants:
    CloudFront:
      # CloudFront HostedZoneId is hardcoded to this value, see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
      HostedZoneId: Z2FDTNDATAQYW2

Resources:

  NakedSite:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref Domain
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
      Tags:
        - Key: ResourceType
          Value: Project
        - Key: Project
          Value: !Ref Project
  
  WWWSite:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'www.${Domain}'
      AccessControl: PublicRead
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref Domain
      Tags:
        - Key: ResourceType
          Value: Project
        - Key: Project
          Value: !Ref Project
          
  NakedRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref Domain
      Type: A
      AliasTarget:
        DNSName: !GetAtt CDN.DomainName
        HostedZoneId: !FindInMap [ Constants, CloudFront, HostedZoneId ]
      HostedZoneId: !Ref HostedZoneId
  
  WWWRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub 'www.${Domain}'
      Type: A
      AliasTarget:
        DNSName: !GetAtt CDN.DomainName
        HostedZoneId: !FindInMap [ Constants, CloudFront, HostedZoneId ]
      HostedZoneId: !Ref HostedZoneId

  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref Domain
          - !Sub 'www.${Domain}'
        CustomErrorResponses:
          - ErrorCode: 404
            ErrorCachingMinTTL: 0
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          AllowedMethods: [ GET, HEAD, OPTIONS ]
          TargetOriginId: StaticSiteOrigin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 0
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        Origins:
          - DomainName: !GetAtt NakedSite.DomainName
            Id: StaticSiteOrigin
            S3OriginConfig:
              OriginAccessIdentity: ''
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref DomainCertificate
          SslSupportMethod: sni-only

  DomainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '*.${Domain}'
      DomainValidationOptions:
        - DomainName: !Sub '*.${Domain}'
          ValidationDomain: !Ref Domain
      Tags:
        - Key: ResourceType
          Value: Project
        - Key: Project
          Value: !Ref Project
 
Outputs:
  StackName:
    Value: !Ref AWS::StackName
  NakedSiteURL:
    Description: URL for the naked site
    Value: !GetAtt NakedSite.WebsiteURL
  NakedSiteDomainName:
    Description: Domain name used by CloudFront
    Value: !GetAtt NakedSite.DomainName
  WWWSiteURL:
    Description: URL for the naked site
    Value: !GetAtt WWWSite.WebsiteURL
  CDNDomainName:
    Description: URL for the CloudFront Distribution
    Value: !GetAtt CDN.DomainName
